spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xrd-catalog-db:5432/xroad_catalog
    username: xroad_catalog_collector
    password: xroad_catalog_collector
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    user: xroad_catalog
    password: secret
    show-summary: verbose
    contexts: users,fi
    parameters:
      users:
        collector:
          username: xroad_catalog_collector
          password: xroad_catalog_collector
        lister:
          username: xroad_catalog_lister
          password: xroad_catalog_lister
  main:
    allow-bean-definition-overriding: true
    web-application-type: none

# X-Road instance parameters
xroad-catalog:
  target:
    xroad-instance: ''
    subsystem-code: ''
    member-class: ''
    member-code: ''
  urls:
    security-server-host: http://ss0:8080
    list-clients-host: ${xroad-catalog.urls.security-server-host}
    webservices-endpoint: ${xroad-catalog.urls.security-server-host}
  pool-size:
    fetch-openapi: 5
    fetch-rest: 5
    fetch-wsdl: 5
    list-methods: 5
  log-storage:
    error-log-length-in-days: 90
    flush-log-time-after-hour: 3
    flush-log-time-before-hour: 4
  tasks:
    collector-interval-min: 5
    fetch-run-unlimited: true
    fetch-time-after-hour: 3
    fetch-time-before-hour: 4
  # Country specific settings
  country:
    fi:
      # if enabled, URLs must be provided in order for Finland specific services and tasks to be executed properly
      # if disabled, all other fi-specific properties can be removed from profile
      enabled: true
      fetch:
        companies:
          pool-size: 10
          url: https://avoindata.prh.fi/bis/v1
        organizations:
          pool-size: 10
          url: https://api.palvelutietovaranto.suomi.fi/api/v11/Organization
        external-limit: 1
        external-update-after-days: 1
        external-interval-min: 5
        external-run-unlimited: true
        external-time-after-hour: 3
        external-time-before-hour: 4
