plugins {
    id 'com.github.hierynomus.license'
    id 'checkstyle'
    id 'pmd'
}

license {
    header = rootProject.file('LICENSE.txt')
    include "**/*.java"
}

licenseMain.source = fileTree('src/main')
licenseTest.source = fileTree('src/test')
licenseFormatMain.source = fileTree('src/main')
licenseFormatTest.source = fileTree('src/test')

checkstyle {
    toolVersion = "10.21.0"
    configDirectory = file("${project.rootDir}/config/checkstyle")
    ignoreFailures = false
    showViolations = false
    enableExternalDtdLoad = true
}

checkstyleMain {
    source = fileTree('src/main/java')
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
}

checkstyleTest {
    source = fileTree('src/test/java')
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
}

pmd {
    consoleOutput = true
    toolVersion = "7.8.0"
    rulesMinimumPriority = 5
    ruleSets = ["${project.rootDir}/config/pmd/custom-ruleset.xml"]
    consoleOutput = true // to print errors in console to be visible in pipeline
}

configurations.checkstyle {
    resolutionStrategy.capabilitiesResolution.withCapability("com.google.collections:google-collections") {
        select("com.google.guava:guava:0")
    }
}
