server:
  port: 4915

spring:
  datasource:
    password: xroad_catalog_collector
    url: jdbc:postgresql://localhost:4910/xroad_catalog
    username: xroad_catalog_collector
  liquibase:
    contexts: users,fi
    parameters:
      users:
        collector:
          password: xroad_catalog_collector
          username: xroad_catalog_collector
        lister:
          password: xroad_catalog_lister
          username: xroad_catalog_lister
    password: secret
    user: xroad_catalog

xroad-catalog:
  collector-interval-min: 5
  features:
    country:
      fi:
        enabled: true
  fetch-companies-pool-size: 1
  fetch-companies-url: https://avoindata.prh.fi/bis/v1
  fetch-external-interval-min: 1
  fetch-openapi-pool-size: 1
  fetch-organizations-pool-size: 1
  fetch-organizations-url: https://api.palvelutietovaranto.suomi.fi/api/v11/Organization
  fetch-rest-pool-size: 1
  fetch-wsdl-pool-size: 1
  list-methods-pool-size: 5
  security-server-host: http://localhost:4310

# Increasing logging levels in local development environment for better debugging
logging:
  level:
    javax.ws.rs: TRACE
    liquibase: TRACE
    org.apache.http: DEBUG
    org.hibernate: ERROR
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.type: TRACE
    org.springframework.beans.factory.support.DefaultListableBeanFactory: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    org.springframework.ws: TRACE
