spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ''
    url: ''
    username: xroad_catalog_collector
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: users
    enabled: true
    parameters:
      users:
        collector:
          password: ''
          username: xroad_catalog_collector
        lister:
          password: ''
          username: xroad_catalog_lister
    password: ''
    show-summary: verbose
    user: xroad_catalog
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  sql:
    init:
      platform: postgres

# X-Road instance parameters
xroad-catalog:
  collector-interval-min: 20
  error-log-length-in-days: 90
  fetch-openapi-pool-size: 10
  fetch-rest-pool-size: 10
  fetch-run-unlimited: false
  fetch-time-after-hour: 3
  fetch-time-before-hour: 4
  fetch-wsdl-pool-size: 10
  flush-log-time-after-hour: 3
  flush-log-time-before-hour: 4
  list-clients-host: ${xroad-catalog.security-server-host}
  list-methods-pool-size: 50
  member-class: ''
  member-code: ''
  security-server-host: ''
  ssl-keystore: /etc/xroad/xroad-catalog/keystore
  ssl-keystore-password: changeit
  subsystem-code: ''
  webservices-endpoint: ${xroad-catalog.security-server-host}
  xroad-instance: ''
  # Country specific settings
  country:
    fi:
      # if enabled, URLs must be provided in order for Finland specific services and tasks to be executed properly
      enabled: false
      fetch:
        companies:
          pool-size: 10
          url: ''
        organizations:
          pool-size: 10
          url: ''
        external-limit: 500
        external-update-after-days: 7
        external-interval-min: 20
        external-run-unlimited: false
        external-time-after-hour: 3
        external-time-before-hour: 4
