server.port=4915
# Security server URLs
xroad-catalog.security-server-host=http://localhost:4310

xroad-catalog.features.country.fi.enabled=true

# Parameters related to the "fi" profile
xroad-catalog.fetch-organizations-url=https://api.palvelutietovaranto.suomi.fi/api/v11/Organization
xroad-catalog.fetch-companies-url=https://avoindata.prh.fi/bis/v1
xroad-catalog.fetch-external-interval-min=1

xroad-catalog.list-methods-pool-size=5
# just one thread since the mock structure is not "threadsafe"
xroad-catalog.fetch-wsdl-pool-size=1
xroad-catalog.fetch-openapi-pool-size=1
xroad-catalog.fetch-rest-pool-size=1
xroad-catalog.fetch-organizations-pool-size=1
xroad-catalog.fetch-companies-pool-size=1

spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:4910/xroad_catalog
spring.datasource.username=xroad_catalog_collector
spring.datasource.password=xroad_catalog_collector
spring.liquibase.contexts=users,fi
spring.liquibase.user=xroad_catalog
spring.liquibase.password=secret
spring.liquibase.parameters.users.collector.username=xroad_catalog_collector
spring.liquibase.parameters.users.collector.password=xroad_catalog_collector
spring.liquibase.parameters.users.lister.username=xroad_catalog_lister
spring.liquibase.parameters.users.lister.password=xroad_catalog_lister

# Increasing logging levels in local development for better debugging
logging.level.javax.ws.rs=TRACE
logging.level.liquibase=TRACE
logging.level.org.apache.http=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.orm.jdbc.extract=TRACE
logging.level.org.hibernate.type=TRACE
logging.level.org.springframework.beans.factory.support.DefaultListableBeanFactory=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=DEBUG
logging.level.org.springframework.ws=TRACE
