# production PostgreSQL settings
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://xrd-catalog-db:5432/xroad_catalog
spring.datasource.username=xroad_catalog_collector
spring.datasource.password=xroad_catalog_collector
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.show-summary=verbose
spring.liquibase.contexts=users
spring.liquibase.user=xroad_catalog
spring.liquibase.password=secret
spring.liquibase.parameters.users.collector.username=xroad_catalog_collector
spring.liquibase.parameters.users.collector.password=xroad_catalog_collector
spring.liquibase.parameters.users.lister.username=xroad_catalog_lister
spring.liquibase.parameters.users.lister.password=xroad_catalog_lister