[versions]
awaitility = "4.3.0"
commonsCompress = "1.28.0"
commonsCsv = "1.14.1"
guava = "33.4.8-jre"
h2 = "2.3.232"
hierynomusLicense = "0.16.1"
httpclient = "5.5"
jackson = "2.19.2"
jakartaRsApi = "4.0.0"
jakartaAnnotationApi = "3.0.0"
json = "20240303"
junitLauncher = "1.13.4"
liquibase = "4.33.0"
lombok = "1.18.38"
mockito = "5.18.0"
postgresql = "42.7.7"
plexusUtils="4.0.2"
sonarqube = "6.3.1.5724"
springBoot = "3.5.4"
springDoc = "2.8.9"
xroadLibs = "7.7.0-SNAPSHOT"
xrd4j = "0.9.0-SNAPSHOT"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
h2-database = { module = "com.h2database:h2", version.ref = "h2" }
http-client = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jakarta = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakartaRsApi" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakartaAnnotationApi" }
json = { module = "org.json:json", version.ref = "json" }
junit-launcer = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitLauncher" }
licenseGradlePlugin = { module = "gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin", version.ref = "hierynomusLicense" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
liquibase-hibernate6 = { module = "org.liquibase.ext:liquibase-hibernate6", version.ref = "liquibase" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
plexus-utils = { module = "org.codehaus.plexus:plexus-utils", version.ref = "plexusUtils" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
spring-boot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-doc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc" }
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version = "2.10.3" }
xroad-configuration-client = { module = "org.niis.xroad:configuration-client", version.ref = "xroadLibs" }
xrd4j-client = { module = "org.niis.xrd4j:client", version.ref = "xrd4j"}
xrd4j-server = { module = "org.niis.xrd4j:server", version.ref = "xrd4j"}

[plugins]
sonarqube = { id  = "org.sonarqube", version.ref = "sonarqube" }
spring-boot = { id  = "org.springframework.boot", version.ref = "springBoot" }