name: xrd-catalog-service-dev

services:
  xrd-catalog-db:
    image: postgres:16-alpine
    ports:
      - 4910:5432
    environment:
      POSTGRES_DB: xroad_catalog
      POSTGRES_USER: xroad_catalog
      POSTGRES_PASSWORD: secret
    volumes:
      - xrd-catalog-db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - xrd-catalog-network
  adminer:
    image: adminer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5080:8080
    depends_on:
      - xrd-catalog-db
    networks:
      - xrd-catalog-network
  xrd-catalog-collector:
    build:
      context: ../.
      dockerfile: docker/collector/Dockerfile
#    environment:
#      SPRING_PROFILES_ACTIVE: fi
#      XROAD-CATALOG_COUNTRY_FI_ENABLED: false
#      LOGGING_LEVEL_LIQUIBASE: TRACE
#      SPRING_LIQUIBASE_CONTEXTS: users
    volumes:
      - ./collector/config:/etc/xroad/xroad-catalog:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - xrd-catalog-db
    networks:
      - xrd-catalog-network
      - xroad-network
  xrd-catalog-lister:
    build:
      context: ../.
      dockerfile: docker/lister/Dockerfile
    volumes:
      - ./lister/config:/etc/xroad/xroad-catalog:ro
      - ./lister/config/configuration-anchor.xml:/etc/xroad/configuration-anchor.xml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8070:8080
    depends_on:
      - xrd-catalog-collector
    networks:
      - xrd-catalog-network
      - xroad-network

volumes:
  xrd-catalog-db-data:
networks:
  xrd-catalog-network:
    name: xrd-catalog-network
    driver: bridge
  xroad-network:
    external: true
