
plugins {
    alias (libs.plugins.spring.boot)
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'jacoco'
    id 'catalogservice.java-checks'
}

group = 'org.niis.xroad.catalog.collector'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

configurations {
    wsimport
}

sourceSets {
    main {
        java.srcDirs = ['src/main/java', 'build/generated-sources/wsimport']
    }
}

bootJar {
    enabled = true
    layered {
        enabled = false
    }
    includeTools = false
}

jar {
    enabled = false
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.WARN
}

springBoot {
    mainClass = 'org.niis.xroad.catalog.collector.CollectorApplication'
}

tasks.register('wsImport') {
    ext.sourcedestdir = layout.buildDirectory.dir("generated-sources/wsimport").get().asFile
    ext.destdir = layout.buildDirectory.dir("generated-classes/wsimport").get().asFile
    ext.wsdl = "${projectDir}/src/main/resources/schema/metaservices.wsdl"

    inputs.files wsdl
    outputs.dir sourcedestdir

    doLast() {
        ant.taskdef name: "wsimport", classname: "com.sun.tools.ws.ant.WsImport",
                classpath: configurations.wsimport.asPath
        ant.mkdir(dir: destdir)
        ant.mkdir(dir: sourcedestdir)

        ant.wsimport(sourcedestdir: sourcedestdir,
                destdir: destdir,
                wsdl: wsdl,
                wsdllocation: "/schema/metaservices.wsdl",
                package: "org.niis.xroad.catalog.collector.wsimport",
                keep: "true") {
            ant.produces(dir: sourcedestdir, includes: "**/*.java")
        }
    }
}

licenseMain.dependsOn wsImport

dependencies {
    implementation project(':xroad-catalog-persistence')
    implementation (libs.jakarta.annotation)
    implementation (libs.jakarta.jaxb)
    implementation (libs.guava)
    implementation (libs.http.client)
    implementation (libs.json)
    implementation (libs.spring.boot.ws)
    implementation (libs.spring.boot.jpa)
    implementation (libs.jackson)
    // Note that bundle seems to break something with CXF and being able top find api bindings, so using separate dependencies here
    implementation (libs.cxf.jaxws)
    implementation (libs.cxf.transport)
    implementation (libs.cxf.core)
    implementation (libs.cxf.spring.starter)
    implementation (libs.lombok)
    implementation (libs.liquibase)
    implementation (libs.xmlunit.core)
    annotationProcessor (libs.lombok)
    wsimport (libs.jaxb.maven)
    implementation (libs.bundles.jaxb)
    compileOnly (libs.liquibase.hibernate6)
    testImplementation (libs.spring.boot.test)
    testRuntimeOnly (libs.junit.launcer)
    testImplementation (libs.mockito)
    testAnnotationProcessor (libs.lombok)
    testImplementation (libs.awaitility)
    testImplementation (libs.h2.database)
}

compileJava.dependsOn wsImport

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    "**/wsimport/*"
            ])
        }))
    }
    reports {
        xml.required = true
    }
}
