plugins {
    alias (libs.plugins.spring.boot) // id "org.springframework.boot" version "${springBootVersion}"
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'jacoco'
}

group 'fi.vrk.xroad.catalog.collector'
sourceCompatibility = 11
targetCompatibility = 11

repositories {
    mavenCentral()
}

configurations {
    wsimport
}

sourceSets {
    main {
        java.srcDirs = ['src/main/java', 'build/generated-sources/wsimport']
    }
}

bootJar {
    enabled = true
    layered {
        enabled = false
    }
}

jar {
    enabled = false
}

springBoot {
    mainClass = 'fi.vrk.xroad.catalog.collector.XRoadCatalogCollector'
}

task wsImport {
    ext.sourcedestdir = "${buildDir}/generated-sources/wsimport"
    ext.destdir = "${buildDir}/generated-classes/wsimport"
    ext.wsdl = "${projectDir}/src/main/resources/schema/metaservices.wsdl"

    inputs.files wsdl
    outputs.dir sourcedestdir

    doLast() {
        project.ant {
            taskdef name: "wsimport", classname: "com.sun.tools.ws.ant.WsImport",
                    classpath: configurations.wsimport.asPath
            mkdir(dir: destdir)
            mkdir(dir: sourcedestdir)

            wsimport(sourcedestdir: sourcedestdir,
                    destdir: destdir,
                    wsdl: wsdl,
                    wsdllocation: "/schema/metaservices.wsdl",
                    package: "fi.vrk.xroad.catalog.collector.wsimport",
                    keep: "true"
            ) {
                produces(dir: sourcedestdir, includes: "**/*.java")
            }
        }
    }
}

dependencies {
    implementation project(':xroad-catalog-persistence')
    implementation (libs.javax.annotation) // implementation ("javax.annotation:javax.annotation-api:${javaxAnnotationVersion}")
    implementation (libs.javax.jaxb) // implementation ("javax.xml.bind:jaxb-api:${javaxJaxbVersion}")
    implementation (libs.guava) // implementation("com.google.guava:guava:${guavaVersion}")
    implementation (libs.http.client) // implementation("org.apache.httpcomponents:httpclient:${httpClientVersion}")
    implementation (libs.json) // implementation("org.json:json:${jsonVersion}")
    implementation (libs.spring.boot.ws) // implementation("org.springframework.boot:spring-boot-starter-web-services:${springBootVersion}")
    implementation (libs.jackson) // implementation("com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}")
    implementation (libs.bundles.akka) // implementation("com.typesafe.akka:akka-actor_3:${akkaVersion}")
                                  // implementation("com.typesafe.akka:akka-slf4j_3:${akkaVersion}")
    implementation (libs.bundles.cxf) // implementation("org.apache.cxf:cxf-rt-frontend-jaxws:${cxfCoreVersion}")
                                 // implementation("org.apache.cxf:cxf-rt-transports-http:${cxfVersion}")
                                 // implementation("org.apache.cxf:cxf-core:${cxfCoreVersion}")
    implementation (libs.lombok) // implementation("org.projectlombok:lombok:${lombokVersion}")
    annotationProcessor (libs.lombok) // annotationProcessor("org.projectlombok:lombok:${lombokVersion}")
    wsimport (libs.jaxb.maven) // wsimport("com.sun.xml.ws:jaxws-maven-plugin:${jaxbVersion}")
    implementation (libs.bundles.jaxb) // implementation("jakarta.xml.ws:jakarta.xml.ws-api:${jaxbVersion}")
                                  // implementation("com.sun.xml.ws:jaxws-rt:${jaxbVersion}")
                                  // implementation("com.sun.xml.ws:jaxws-tools:${jaxbVersion}")
    testImplementation (libs.spring.boot.test) {
        exclude group: 'org.mockito', module :'mockito-core'
    }
    /*testImplementation("org.springframework.boot:spring-boot-starter-test:${springBootVersion}") {
                exclude group: 'org.mockito', module :'mockito-core'
    }*/
    testImplementation (libs.mockito.inline) // testImplementation("org.mockito:mockito-inline:${mockitoInlineVersion}")
    testImplementation (libs.akka.testkit) // testImplementation("com.typesafe.akka:akka-testkit_3:${akkaVersion}")
    testImplementation (libs.lombok) // testImplementation("org.projectlombok:lombok:${lombokVersion}")
    testAnnotationProcessor (libs.lombok) // testAnnotationProcessor("org.projectlombok:lombok:${lombokVersion}")
    testImplementation (libs.javax.annotation) // testImplementation("javax.annotation:javax.annotation-api:${javaxAnnotationVersion}")
    testImplementation (libs.javax.jaxb) // testImplementation("javax.xml.bind:jaxb-api:${javaxJaxbVersion}")
}

compileJava.dependsOn wsImport

test {
    useJUnitPlatform {
        includeEngines 'junit-jupiter'
    }
    systemProperty 'spring.config.name', 'collector,catalogdb'
    finalizedBy jacocoTestReport
}

bootRun {
    systemProperty 'spring.config.name', 'collector,catalogdb'
}

jacocoTestReport {
    dependsOn test
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    "**/wsimport/*"
            ])
        }))
    }
    reports {
        xml.required = true
    }
}
