spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ''
    username: xroad_catalog_lister
    password: ''
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# OpenAPI documentation
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
    urls-primary-name: v2

# X-Road configuration-client parameters
xroad:
  common.configuration-path: /etc/xroad/globalconf
  proxy.configuration-anchor-file: /etc/xroad/configuration-anchor.xml
  configuration-client:
    port: 5665
    admin-port: 5675
    update-interval: 60
    allowed-federations: none
    proxy-configuration-backup-cron: 0 15 3 * * ?
    global_conf_tls_cert_verification: true
    global_conf_hostname_verification: true

# X-Road instance parameters
xroad-catalog:
  shared-params-file: ${xroad.common.configuration-path}/<INSTANCE_IDENTIFIER>/shared-params.xml
  configuration-client.enabled: true

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        ws: DEBUG
  pattern:
    level: "%5p [%X{requestId:-}]"
