server.port=4920

xroad-catalog.features.country.fi.enabled=true

xroad-catalog.shared-params-file=/etc/xroad/globalconf/<INSTANCE_IDENTIFIER>/shared-params.xml

spring.jpa.show-sql=true
spring.liquibase.contexts=users,fi
spring.datasource.username=xroad_catalog_lister
spring.datasource.password=xroad_catalog_lister

# Increasing logging levels in local development for better debugging
logging.level.javax.ws.rs=TRACE
logging.level.liquibase=TRACE
logging.level.org.apache.http=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.orm.jdbc.extract=TRACE
logging.level.org.hibernate.type=TRACE
logging.level.org.springframework.beans.factory.support.DefaultListableBeanFactory=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=DEBUG
logging.level.org.springframework.ws=TRACE
