logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.org.hibernate=ERROR

xroad-catalog.shared-params-file=/etc/xroad/globalconf/<INSTANCE_IDENTIFIER>/shared-params.xml

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api-docs
springdoc.packagesToScan=org.niis.xroad,fi.dvv.xroad

# production PostgreSQL settings
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:4910/xroad_catalog
spring.datasource.username=xroad_catalog_lister
spring.datasource.password=xroad_catalog_lister
spring.liquibase.enabled=false
