logging:
  level:
    org:
      apache:
        http: DEBUG
      springframework:
        web:
          server:
            adapter:
              HttpWebHandlerAdapter: DEBUG
          nodeValue: TRACE
        ws: TRACE
        beans:
          factory:
            support:
              DefaultListableBeanFactory: DEBUG
        security: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE
            extract: TRACE
        nodeValue: ERROR
        type: TRACE
    liquibase: TRACE
    javax:
      ws:
        rs: TRACE
xroad-catalog:
  shared-params-file: /etc/xroad/globalconf/<INSTANCE_IDENTIFIER>/shared-params.xml
  features:
    country:
      fi:
        enabled: 'true'
spring:
  datasource:
    password: xroad_catalog_lister
    username: xroad_catalog_lister
    url: jdbc:postgresql://localhost:4910/xroad_catalog
server:
  port: '4920'
