xroad-catalog.shared-params-file=/etc/xroad/globalconf/<INSTANCE_IDENTIFIER>/shared-params.xml

spring.jpa.show-sql=true
spring.liquibase.contexts=users,fi
spring.datasource.username=xroad_catalog_lister
spring.datasource.password=xroad_catalog_lister
