logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.org.hibernate=ERROR
# Hibernate log configuration
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.orm.jdbc.extract=TRACE

xroad-catalog.shared-params-file=/etc/xroad/globalconf/<INSTANCE_IDENTIFIER>/shared-params.xml

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api-docs
springdoc.packagesToScan=fi.vrk.xroad
