logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.org.hibernate=ERROR

xroad-catalog.shared-params-file=/etc/xroad/globalconf/<INSTANCE_IDENTIFIER>/shared-params.xml

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api-docs
springdoc.packagesToScan=fi.vrk.xroad

spring.jpa.hibernate.ddl-auto=none

# production PostgreSQL settings
spring.jpa.database=POSTGRESQL
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.database.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/xroad_catalog
spring.datasource.username=xroad_catalog
spring.datasource.password=secret
spring.liquibase.enabled=false