CREATE ROLE xroad_catalog_lister NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 PASSWORD '${users.lister.password}';
GRANT USAGE ON SCHEMA public TO xroad_catalog_lister;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO xroad_catalog_lister;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO xroad_catalog_lister;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO xroad_catalog_lister;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO xroad_catalog_lister;