spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xrd-catalog-db:5432/xroad_catalog
    username: xroad_catalog_lister
    password: xroad_catalog_lister
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# OpenAPI documentation
springdoc:
  packagesToScan: org.niis.xroad,fi.dvv.xroad
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs

# X-Road configuration-client parameters
xroad:
  conf:
    path: /etc/xroad/

# X-Road instance parameters
xroad-catalog:
  shared-params-file: ${xroad.conf.path}globalconf/DEV/shared-params.xml
  country:
    fi:
      enabled: true

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        ws: DEBUG
