spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xrd-catalog-db:5432/xroad_catalog
    username: xroad_catalog_lister
    password: xroad_catalog_lister
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# OpenAPI documentation
springdoc:
  packagesToScan: org.niis.xroad,fi.dvv.xroad
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs

# X-Road configuration-client parameters
xroad:
  common.configuration-path: /etc/xroad/globalconf
  proxy.configuration-anchor-file: /etc/xroad/configuration-anchor.xml
  configuration-client:
    port: 5665
    admin-port: 5675
    update-interval: 60
    allowed-federations: none
    proxy-configuration-backup-cron: 0 15 3 * * ?
    global_conf_tls_cert_verification: true
    global_conf_hostname_verification: true

# X-Road instance parameters
xroad-catalog:
  shared-params-file: ${xroad.common.configuration-path}/<INSTANCE_IDENTIFIER>/shared-params.xml
  country.fi.enabled: true
  configuration-client.enabled: true

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
        ws: DEBUG
