name: Publish images
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["X-Road-Catalog tests"]
#    types: [completed]
#    branches: [develop, XRDCAT-28-**]
env:
  REGISTRY: ghcr.io
  XROAD_HOME: ${{ github.workspace }}
jobs:
  BuildAndPublish:
    name: Setup Environment
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        service: [collector, listener]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
          cache-cleanup: always
          dependency-graph: generate-and-submit
          add-job-summary-as-pr-comment: always
      - name: Build JARs (skipping tests)
        run: ./gradlew --no-daemon build -x test
      - name: print working directory
        run: pwd
      - name: List JAR files
        run: ls -lah xroad-catalog-${{ matrix.service }}/build/libs
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push xrddev-catalog-${{ matrix.service }}'s Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/nordic-institute/xrddev-catalog-${{ matrix.service }}:latest
      - name: Clean old ${{ matrix.service }} images
        uses: snok/container-retention-policy@v2
        with:
          image-names: xrddev-catalog-${{ matrix.service }}
          cut-off: 1 week ago UTC
          timestamp-to-use: created_at
          account-type: org
          org-name: nordic-institute
          keep-at-least: 1
          token-type: github-token
          token: ${{ secrets.GITHUB_TOKEN }}
